#### Starting boot2docker vm
## boot2docker status
## boot2docker up
##
#### Getting it's IP (for access to elasticsearch)
## boot2docker ssh
## ifconfig
## OR
## boot2docker ip
## --> you can access ElasticSearch via http://IP-FROM-ABOVE:9200
##
#### Init the Docker environment vars
## eval "$(boot2docker shellinit)"
## 
##
#### Building an image based on this dockerfile:
## docker build -t elasticsearch <DIR_OF_Dockerfile>
##
#### Running the image
## docker run -it -p 9200:9200 -p 9300:9300 elasticsearch bash
##
## docker ps
## docker images
##
#### Removing older images
## docker ps -a (grab the CONTAINERID)
## docker rm CONTAINERID
##

# Dockerfile
FROM ubuntu:latest
RUN apt-get install software-properties-common -y
RUN apt-get update
RUN add-apt-repository ppa:webupd8team/java -y && apt-get update
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && apt-get install -y oracle-java8-installer
RUN wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.5.1.deb
RUN dpkg -i elasticsearch*deb
RUN /etc/init.d/elasticsearch start
RUN /usr/share/elasticsearch/bin/plugin --install mobz/elasticsearch-head
RUN /usr/share/elasticsearch/bin/plugin --install org.codelibs/elasticsearch-reindexing/1.4.2
RUN apt-get install curl -y
RUN apt-get install tmux -y
RUN apt-get install nmap -y

# minor cleanup
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /var/cache/oracle-jdk8-installer

WORKDIR /data

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ENV ES_HOME /usr/share/elasticsearch

CMD ["bash"]
